## activemq-artemis image version
## ref: https://hub.docker.com/r/vromero/activemq-artemis/tags
##
imageTag: "2.6.1"

## Create a database user
##
artemisUser: artemis
artemisPassword: simetraehcapa

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
#imagePullPolicy: IfNotPresent
imagePullPolicy: Always

replicas: 2

# nameOverride replaces the computed chart name with this given name. 
# nameOverride: 

# namePrefix sets the prefix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
# namePrefix:

# nameSuffix sets the suffix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
# nameSuffix: 

global:
# namePrefix sets the global prefix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
#   namePrefix: Global prefix
# nameSuffix sets the global suffix for the fullname in the template "global prefix + prefix + name + suffix + global suffix"
#   nameSuffix: Global suffix

deployment:
  ## Artemis Deployment annotations
  annotations: {}
  #   name: value
replica:
  ## Artemis Replicas annotations
  annotations: {}
  ## Read more about kube2iam to provide access to s3 https://github.com/jtblin/kube2iam
  #   iam.amazonaws.com/role: role-arn

## Persist data to a persitent volume
persistence:
  testJournalPerformance: AUTO
  enabled: false
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m


# A load balander might confuse Minikube when installing with Helm and --wait
# Probably this is only useful for minikube environments and CI
loadbalancer:
  enabled: true
