apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  {{- range $key, $val:= .Values.brokers }}
  {{ $key }}: |
    {{ $val }}
  {{- end }}
  jgroups.xml: |
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="urn:org:jgroups"
          xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    
      <TCP
          bind_port="7800" 
          loopback="false"
          recv_buf_size="${tcp.recv_buf_size:5M}"
          send_buf_size="${tcp.send_buf_size:5M}"
          max_bundle_size="64K"
          max_bundle_timeout="30"
          use_send_queues="true"
          sock_conn_timeout="300"

          timer_type="new3"
          timer.min_threads="4"
          timer.max_threads="10"
          timer.keep_alive_time="3000"
          timer.queue_max_size="500"

          thread_pool.enabled="true"
          thread_pool.min_threads="2"
          thread_pool.max_threads="8"
          thread_pool.keep_alive_time="5000"
          thread_pool.queue_enabled="true"
          thread_pool.queue_max_size="10000"
          thread_pool.rejection_policy="discard"

          oob_thread_pool.enabled="true"
          oob_thread_pool.min_threads="1"
          oob_thread_pool.max_threads="8"
          oob_thread_pool.keep_alive_time="5000"
          oob_thread_pool.queue_enabled="false"
          oob_thread_pool.queue_max_size="100"
          oob_thread_pool.rejection_policy="discard"/>

      <org.jgroups.protocols.kubernetes.KUBE_PING
        namespace="default" />
      
      <!-- labels="${KUBE_LABEL:cluster=nyc}" -->
      
      <MERGE3  
        min_interval="10000"
        max_interval="30000"/>

      <FD_SOCK/>
      <FD timeout="3000" max_tries="3" />

      <VERIFY_SUSPECT timeout="1500"  />

      <BARRIER />
      
      <pbcast.NAKACK2 use_mcast_xmit="false"
                      discard_delivered_msgs="true"/>
      
      <UNICAST3 />
      
      <pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
                    max_bytes="4M"/>
      <pbcast.GMS print_local_addr="true" join_timeout="2000"
                  view_bundling="true"/>
      
      <MFC max_credits="2M"
          min_threshold="0.4"/>
      
      <FRAG2 frag_size="60K"  />
      
      <!--RSVP resend_interval="2000" timeout="10000"/-->
      <pbcast.STATE_TRANSFER/>

      <TRACE/>
      
    </config>

  template.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">

        <jmx-management-enabled>true</jmx-management-enabled>
        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $relname := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $namespace := .Release.Namespace -}}

        <connectors>
          <connector name="netty-connector">tcp://0.0.0.0:61617</connector>
        </connectors>

        <!-- Acceptors -->
        <acceptors>
          <acceptor name="netty-acceptor">tcp://0.0.0.0:61617</acceptor>
        </acceptors>

        <broadcast-groups>
          <broadcast-group name="my-broadcast-group">
            <broadcast-period>5000</broadcast-period>
            <jgroups-file>jgroups.xml</jgroups-file>
            <jgroups-channel>active_broadcast_channel</jgroups-channel>
            <connector-ref>netty-connector</connector-ref>
          </broadcast-group>
        </broadcast-groups>

        <discovery-groups>
          <discovery-group name="my-discovery-group">
              <jgroups-file>jgroups.xml</jgroups-file>
              <jgroups-channel>active_broadcast_channel</jgroups-channel>
              <refresh-timeout>10000</refresh-timeout>
          </discovery-group>
        </discovery-groups>

        <cluster-connections>
          <cluster-connection name="my-cluster">
              <connector-ref>netty-connector</connector-ref>
              <retry-interval>500</retry-interval>
              <use-duplicate-detection>true</use-duplicate-detection>
              <message-load-balancing>STRICT</message-load-balancing>
              <max-hops>1</max-hops>
              <discovery-group-ref discovery-group-name="my-discovery-group"/>
          </cluster-connection>
       </cluster-connections>

       <ha-policy>
         <replication>
           <master>
             <!--we need this for auto failback-->
             <check-for-live-server>false</check-for-live-server>
           </master>
         </replication>
       </ha-policy>

      </core>

    </configuration>

  configure-cluster.xslt: |
    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:activemq="urn:activemq" xmlns:jms="urn:activemq:jms" xmlns:core="urn:activemq:core"
      exclude-result-prefixes="activemq jms core">

        <xsl:output omit-xml-declaration="yes"/>

        <xsl:param name="hostname" />

        <xsl:template match="node()|@*">
          <xsl:copy>
             <xsl:apply-templates select="node()|@*"/>
          </xsl:copy>
        </xsl:template>

    </xsl:stylesheet>

  configure-cluster.sh: |
    cp /var/lib/artemis/etc-override-template/broker-* /var/lib/artemis/etc-override | true
    xmlstarlet tr /var/lib/artemis/etc-override-template/configure-cluster.xslt -s hostname=$(hostname) /var/lib/artemis/etc-override-template/template.xml > /var/lib/artemis/etc-override/broker-00.xml
    sed -i "s/^JAVA_ARGS=\"/JAVA_ARGS=\"-Djgroups.bind_addr=\"$(hostname)\" /g" /var/lib/artemis/etc/artemis.profile

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tools-{{ template "fullname" . }}
data:
  is-backup.sh: |
    curl -s http://localhost:8161/jolokia/read/org.apache.activemq.artemis:brokerName=%220.0.0.0%22,module=Core,serviceType=Server,type=Broker/Backup | jq .value
