apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:
  template-common.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">

        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $fullname := include "artemis.fullname" . -}}
        {{- $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        {{- $releaseNamespace := .Release.Namespace -}}
        <connectors>
          {{range $i,$t := until (int .Values.replicas)}}
            <connector name="{{ $fullname }}-{{ $i }}">tcp://{{ $fullname }}-{{ $i }}.{{ $releaseName }}.{{ $releaseNamespace }}.svc.cluster.local:61616</connector>
          {{end}}
        </connectors>

        <cluster-connections>
          <cluster-connection name="{{ $releaseName }}">
            <address>jms</address>
            <connector-ref>{{ $fullname }}-0</connector-ref>
            <retry-interval>500</retry-interval>
            <retry-interval-multiplier>1.1</retry-interval-multiplier>
            <max-retry-interval>5000</max-retry-interval>
            <initial-connect-attempts>-1</initial-connect-attempts>
            <reconnect-attempts>-1</reconnect-attempts>

            <message-load-balancing>OFF</message-load-balancing>
            <max-hops>1</max-hops>

            <static-connectors>
              {{ range $i,$t := until (int .Values.replicas) }}
                <connector-ref>{{ $fullname }}-{{ $i }}</connector-ref>
              {{ end }}
            </static-connectors>

         </cluster-connection>
       </cluster-connections>
      </core>
    </configuration>

  template-master.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <ha-policy>
          <replication>
            <master>
              <group-name>to-be-set-by-configure-cluster.sh</group-name>
              <!--we need this for auto failback-->
              <check-for-live-server>false</check-for-live-server>
            </master>
          </replication>
        </ha-policy>
      </core>
    </configuration>
  
  template-slave.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        <ha-policy>
          <replication>
            <slave>
              <group-name>to-be-set-by-configure-cluster.sh</group-name>
            </slave>
          </replication>
        </ha-policy>
      </core>
    </configuration>

  configure-cluster.sh: |
    
    {{ $name := default .Chart.Name .Values.nameOverride }}
    {{ $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}

    set -e
    HOST_GROUP_NAME=$(echo ${HOSTNAME} | sed -re 's/(.*)-[0-9]+/\1/')
    HOST_INDEX=$(echo ${HOSTNAME} | sed -re 's/.*-([0-9]+)/\1/')
    cp /var/lib/artemis/etc-override-template/template-common.xml /var/lib/artemis/etc-override/broker-10.xml
    echo Host index is ${HOST_INDEX}
    if [ "$(( HOST_INDEX % 2))" -eq 0 ]; then 
      echo Assigning node as master
      cp /var/lib/artemis/etc-override-template/template-master.xml /var/lib/artemis/etc-override/broker-11.xml 

      GROUP_NAME=${HOST_GROUP_NAME}-$((${HOST_INDEX}))
      echo Setting the group-name for master to ${GROUP_NAME}
      xmlstarlet ed -L \
      -N activemq="urn:activemq" \
      -N core="urn:activemq:core" \
      -u "/activemq:configuration/core:core/core:ha-policy/core:replication/core:master/core:group-name" \
      -v "${GROUP_NAME}" /var/lib/artemis/etc-override/broker-11.xml
    else
      echo Assigning node as slave
      cp /var/lib/artemis/etc-override-template/template-slave.xml /var/lib/artemis/etc-override/broker-11.xml

      GROUP_NAME=${HOST_GROUP_NAME}-$((${HOST_INDEX} - 1))
      echo Setting the group-name for slave to ${GROUP_NAME}
      xmlstarlet ed -L \
      -N activemq="urn:activemq" \
      -N core="urn:activemq:core" \
      -u "/activemq:configuration/core:core/core:ha-policy/core:replication/core:slave/core:group-name" \
      -v "${GROUP_NAME}" /var/lib/artemis/etc-override/broker-11.xml
    fi
  
    echo Setting the connector-ref to $(hostname)
    xmlstarlet ed -L \
      -N activemq="urn:activemq" \
      -N core="urn:activemq:core" \
      -u "/activemq:configuration/core:core/core:cluster-connections/core:cluster-connection[@name='{{ $releaseName }}']/core:connector-ref" \
      -v "$(hostname)" /var/lib/artemis/etc-override/broker-10.xml

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tools-{{ include "artemis.fullname" . }}
data:
  is-backup.sh: |
    curl -s http://localhost:8161/jolokia/read/org.apache.activemq.artemis:brokerName=%220.0.0.0%22,module=Core,serviceType=Server,type=Broker/Backup | jq .value

