apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  broker-template.xml: |
    <configuration xmlns="urn:activemq"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">

      <core xmlns="urn:activemq:core">

        <cluster-user>exampleUser</cluster-user>
        <cluster-password>secret</cluster-password>

        {{- $name := default .Chart.Name .Values.nameOverride -}}
        {{- $relname := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
        <connectors>
          {{range $i,$t := until (int .Values.replicas)}}
            <connector name="{{$relname}}-{{$i}}">tcp://{{$relname}}-{{$i}}.{{$relname}}.default.svc.cluster.local:61616</connector>
          {{end}}
        </connectors>

        <cluster-connections>
          <cluster-connection name="replication-cluster">
            <address>jms</address>
            <connector-ref>{{$relname}}-0</connector-ref>
            <retry-interval>1000</retry-interval>
            <message-load-balancing>ON_DEMAND</message-load-balancing>
            <max-hops>1</max-hops>

            <static-connectors allow-direct-connections-only="true">
              {{range $i,$t := until (int .Values.replicas)}}
                <connector-ref>{{$relname}}-{{$i}}</connector-ref>
              {{end}}
            </static-connectors>

         </cluster-connection>
       </cluster-connections>

       <ha-policy>
         <replication>
           <master>
             <!--we need this for auto failback-->
             <check-for-live-server>false</check-for-live-server>
           </master>
           <!--slave/-->
         </replication>
       </ha-policy>

      </core>

    </configuration>

  configure-cluster.xslt: |
    <xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:activemq="urn:activemq" xmlns:jms="urn:activemq:jms" xmlns:core="urn:activemq:core">

        <xsl:output omit-xml-declaration="yes"/>

        <xsl:param name="hostname" />

        <xsl:template match="node()|@*">
          <xsl:copy>
             <xsl:apply-templates select="node()|@*"/>
          </xsl:copy>
        </xsl:template>

        <xsl:template match="//core:core/core:cluster-connections/core:cluster-connection/core:connector-ref">
          <core:connector-ref><xsl:value-of select="$hostname" /></core:connector-ref>
        </xsl:template>

        <xsl:template match="//core:core/core:cluster-connections/core:cluster-connection/core:static-connectors/core:connector-ref">
          <xsl:choose>
            <xsl:when test="text()=$hostname"/>
            <xsl:otherwise>
              <xsl:copy>
                <xsl:apply-templates select="@*|node()"/>
              </xsl:copy>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:template>

    </xsl:stylesheet>

  configure-cluster.sh: |
    cp /var/lib/artemis/etc-override-template/* /var/lib/artemis/etc-override
    xmlstarlet tr /var/lib/artemis/etc-override-template/configure-cluster.xslt -s hostname=$(hostname) /var/lib/artemis/etc-override-template/broker-template.xml > /var/lib/artemis/etc-override/broker.xml
