apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "artemis.fullname" . }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
spec:
  serviceName: {{ include "artemis.fullname" . }}
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "artemis.name" . }}
      release: {{ .Release.Name | quote }}    
  template:
    metadata:
      name: {{ include "artemis.fullname" . }}
      annotations:
{{ toYaml .Values.replica.annotations | indent 8 }}
      labels:
        app: {{ template "artemis.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      strategy:
        type: Recreate
      initContainers:
      - name: remove-lost-found
        image: "openjdk:8-jre-alpine"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command: ["rm", "-fr", "/var/lib/artemis/data/lost+found"]
        volumeMounts:
          - name: "data"
            mountPath: "/var/lib/artemis/data"
      #- name: set-volume-permissions
      #  image: "openjdk:8-jre-alpine"
      #  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
      #  command: ["chown", "-R", "artemis.artemis", "/var/lib/artemis/data"]
      #  volumeMounts:
      #    - name: "data"
      #      mountPath: "/var/lib/artemis/data"
      - name: configure-cluster
        image: "vromero/activemq-artemis:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command: ["/bin/sh", "/var/lib/artemis/etc-override-template/configure-cluster.sh"]
        volumeMounts:
          - name: "config-override-template"
            mountPath: "/var/lib/artemis/etc-override-template"
          - name: "config-override"
            mountPath: "/var/lib/artemis/etc-override"
      containers:
      - name: {{ include "artemis.fullname" . }}
        image: "vromero/activemq-artemis:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "artemis.fullname" . }}
              key: artemis-password
        - name: ARTEMIS_USERNAME
          value: {{ default "artemis" .Values.artemisUser | quote }}
        - name: ARTEMIS_PERF_JOURNAL
          value: {{ default "AUTO" .Values.persistence.testJournalPerformance | quote }}
        ports:
        - name: http
          containerPort: 8161
        - name: core
          containerPort: 61616
        - name: amqp
          containerPort: 5672
        - name: jmxexporter
          containerPort: 9404
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/artemis/data
        - name: config-override
          mountPath: /var/lib/artemis/etc-override
        - name: config-override-template
          mountPath: /var/lib/artemis/etc-override-template
        - name: tools
          mountPath: /opt/tools
      volumes:
      - name: config-override
        emptyDir: {}
      - name: tools
        configMap:
          name: tools-{{ include "artemis.fullname" . }}
      - name: config-override-template
        configMap:
          name: {{ include "artemis.fullname" . }}
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "artemis.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
