apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"    
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccountName: {{ template "fullname" . }}
      initContainers:
      - name: configure-cluster
        image: "vromero/activemq-artemis:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command: ["/bin/sh", "/var/lib/artemis/etc-override-template/configure-cluster.sh"]
        volumeMounts:
          - name: "config-override-template"
            mountPath: "/var/lib/artemis/etc-override-template"
          - name: "config-override"
            mountPath: "/var/lib/artemis/etc-override"
      containers:
      - name: {{ template "fullname" . }}
        image: "vromero/activemq-artemis:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ARTEMIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: artemis-password
        - name: ARTEMIS_USERNAME
          value: {{ default "artemis" .Values.artemisUser | quote }}
        - name: ARTEMIS_PERF_JOURNAL
          value: {{ default "AUTO" .Values.persistence.testJournalPerformance | quote }}
        ports:
        - name: http
          containerPort: 8161
        - name: core
          containerPort: 61616
        - name: amqp
          containerPort: 5672
        - name: jmxexporter
          containerPort: 9404
        - name: jgroupsa
          containerPort: 7500
        - name: jgroupsb
          containerPort: 7800
        - name: jgroupsc
          containerPort: 8888  
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/artemis/data
        - name: config-override
          mountPath: /var/lib/artemis/etc-override
        - name: config-override-template
          mountPath: /var/lib/artemis/etc-override-template
        - name: jgroups
          mountPath: /var/lib/artemis/etc/jgroups.xml
          subPath: jgroups.xml
        - name: tools
          mountPath: /opt/tools
      volumes:
      - name: config-override
        emptyDir: {}
      - name: jgroups
        configMap:
          name: {{ template "fullname" . }}
      - name: tools
        configMap:
          name: tools-{{ template "fullname" . }}
      - name: config-override-template
        configMap:
          name: {{ template "fullname" . }}
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
